[package]
name = "zenoh-test-tools"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "z_pub"
path = "src/z_pub.rs"

[[bin]]
name = "z_sub"
path = "src/z_sub.rs"

[dependencies]
zenoh = { version = "1", default-features = false, features = ["transport_tcp"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync"] }
