//! zenoh-link-iroh — Iroh QUIC P2P transport plugin for Zenoh.
//!
//! Compiled as cdylib (.so), loaded by zenohd with `-P iroh_link`.
//! After loading, "iroh/<node_id>" becomes a valid endpoint scheme.

use std::sync::Arc;
use tracing::info;
use zenoh::internal::plugins::{RunningPlugin, RunningPluginTrait};
use zenoh::internal::runtime::DynamicRuntime;
use zenoh_plugin_trait::declare_plugin;
use zenoh_plugin_trait::{Plugin, PluginControl};
use zenoh_result::ZResult;

// ---------------------------------------------------------------------------
// Plugin type
// ---------------------------------------------------------------------------

pub struct IrohPlugin;

// ---------------------------------------------------------------------------
// Running instance
// ---------------------------------------------------------------------------

/// Holds the Iroh Endpoint that this plugin manages.
pub struct IrohLinkInstance {
    _endpoint: Arc<iroh::Endpoint>,
}

impl PluginControl for IrohLinkInstance {}

impl RunningPluginTrait for IrohLinkInstance {}

// ---------------------------------------------------------------------------
// Plugin trait impl
// ---------------------------------------------------------------------------

impl Plugin for IrohPlugin {
    type StartArgs = DynamicRuntime;
    type Instance = RunningPlugin;

    const DEFAULT_NAME: &'static str = "iroh_link";
    const PLUGIN_VERSION: &'static str = env!("CARGO_PKG_VERSION");
    const PLUGIN_LONG_VERSION: &'static str = env!("CARGO_PKG_VERSION");

    fn start(_name: &str, _args: &Self::StartArgs) -> ZResult<Self::Instance> {
        info!("Iroh plugin starting");

        // Create a temporary tokio runtime to block on the async iroh bind
        // (the start function is synchronous per the Plugin trait).
        let rt = tokio::runtime::Runtime::new()?;

        let endpoint = rt.block_on(async {
            iroh::Endpoint::builder()
                .discovery_n0()
                .alpns(vec![b"zenoh-iroh/1.0".to_vec()])
                .bind()
                .await
        })?;

        let node_id = endpoint.node_id();
        info!("Iroh endpoint ready, node_id: {node_id}");

        Ok(Box::new(IrohLinkInstance {
            _endpoint: Arc::new(endpoint),
        }))
    }
}

// ---------------------------------------------------------------------------
// Dynamic-library entry points (generated by declare_plugin! macro)
// ---------------------------------------------------------------------------

declare_plugin!(IrohPlugin);
